pull_request_rules:
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - -closed
      - -draft
      - author != renovate[bot]
      - "#approved-reviews-by >= 0"
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
  - name: assign PR to its author
    conditions:
      - author != renovate[bot]
      - "#assignees = 0"
    actions:
      assign:
        add_users:
          - "{{author}}"
  - name: Delete head branch after merge
    conditions:
      - merged
      - author != renovate[bot]
    actions:
      delete_head_branch:
        force: false
  - name: rebase pull request when it's more than 10 commits behind main
    conditions:
      - base = main
      - -closed
      - -draft
      - author != renovate[bot]
      - "#commits-behind >= 10"
    actions:
      rebase:
  - name: Convert to draft on failure
    conditions:
      - -closed
      - -draft
      - author != renovate[bot]
      - "#check-failure > 0"
    actions:
      edit:
        draft: true
  - name: toggle labels based on CI state
    conditions:
      - -closed
      - -draft
      - "#check-failure > 0"
    actions:
      label:
        toggle:
          - "CI:fail"
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - -closed
      - -draft
      - author != renovate[bot]
      - conflict
    actions:
      label:
        toggle:
          - conflict
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: Force issue association
    description: Make sure PR has an associated issue
    if:
      - base = main
      - author != renovate[bot]
    success_conditions:
      - body ~= Fixes
