pull_request_rules:
  - name: Auto-assign author when unassigned
    description: Automatically assign the pull request author if a pull request is
      open and has no assignees.
    conditions:
      - -closed
      - "#assignee = 0"
    actions:
      assign:
        add_users:
          - "{{author}}"
  - name: Request review from user
    description: Request review from a specific user when checks are green.
    conditions:
      - -closed
      - "#approved-reviews-by = 0"
      - "#changes-requested-reviews-by = 0"
      - review-requested != @wkenned1
    actions:
      request_reviews:
        users:
          - wkenned1
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: Force issue association
    description: Make sure PR has an associated issue
    if:
      - base = main
    success_conditions:
      - body ~= Fixes
