pull_request_rules:
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - "#approved-reviews-by >= 0"
    actions:
      merge:
        method: squash
  - name: assign PR to its author
    conditions:
      - "#assignees = 0"
    actions:
      assign:
        add_users:
          - "{{author}}"
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
  # - name: Convert to draft on failure
  #   conditions:
  #     - "#check-failure > 0"
  #   actions:
  #     edit:
  #       draft: true
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: Force issue association
    description: Make sure PR has an associated issue
    if:
      - base = main
    success_conditions:
      - body ~= Fixes
