pull_request_rules:
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
  - name: Convert to draft on failure
    conditions:
      - "#check-failure > 0"
    actions:
      edit:
        draft: true
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
merge_protections:
  - name: Require at least one review
    if:
      - base = main
    success_conditions:
      - "#approved-reviews-by >= 0"
  - name: Enforce status checks
    description: Make sure that all status checks passed
    if:
      - base = main
    success_conditions:
      - check-success = build
      - check-success = format
      - check-success = lint
      - check-success = typecheck
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: Force issue association
    description: Make sure PR has an associated issue
    if:
      - base = main
    success_conditions:
      - body ~= Fixes
