packages:
  - apps/*
  - packages/*

catalog:
  '@astrojs/check': 0.9.4
  '@astrojs/starlight': ^0.35.2
  '@biomejs/biome': 2.2.4
  astro: 5.13.6
  only-allow: ^1.2.1
  oxlint: 1.15.0
  sharp: 0.34.3
  tsdown: ^0.15.0
  tsx: ^4.20.5
  turbo: ^2.5.6
  typescript: ^5.9.2

catalogMode: strict

cleanupUnusedCatalogs: true
