packages:
  - apps/*
  - packages/*

catalog:
  '@astrojs/check': 0.9.4
  '@astrojs/starlight': 0.35.2
  '@better-auth/cli': 1.3.13
  '@biomejs/biome': 2.2.4
  '@cloudflare/vite-plugin': ^1.13.12
  '@hookform/resolvers': 5.2.2
  '@measured/puck': 0.20.2
  '@polar-sh/better-auth': 1.1.4
  '@polar-sh/sdk': 0.34.16
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': 1.2.6
  '@tailwindcss/vite': 4.1.13
  '@tanstack/devtools-vite': 0.3.3
  '@tanstack/react-devtools': 0.7.0
  '@tanstack/react-query': 5.90.2
  '@tanstack/react-query-devtools': 5.90.2
  '@tanstack/react-router': 1.132.47
  '@tanstack/react-router-devtools': 1.132.51
  '@tanstack/react-router-ssr-query': 1.132.47
  '@tanstack/react-start': 1.132.51
  '@types/better-sqlite3': 7.6.13
  '@types/node': 24.5.2
  '@types/react': 19.1.13
  '@types/react-dom': 19.1.9
  '@vitejs/plugin-react': 5.0.3
  '@xstate/react': 6.0.0
  astro: 5.13.6
  babel-plugin-react-compiler: 19.1.0-rc.3
  better-auth: 1.3.26
  better-sqlite3: 12.3.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  effect: 3.17.14
  kysely: 0.28.7
  kysely-d1: 0.4.0
  lucide-react: 0.544.0
  only-allow: 1.2.1
  oxlint: 1.17.0
  react: 19.1.1
  react-dom: 19.1.1
  react-hook-form: 7.63.0
  shadcn: 3.3.1
  sharp: 0.34.3
  slugify: 1.6.6
  sonner: 2.0.7
  sqlite: 5.1.1
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.13
  tsdown: 0.15.6
  tsx: 4.20.6
  turbo: 2.5.6
  tw-animate-css: 1.3.8
  typescript: 5.9.3
  vite: 7.1.9
  wrangler: 4.42.2
  xstate: 5.22.0

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

onlyBuiltDependencies:
  - msw
  - workerd

strictPeerDependencies: true

updateNotifier: false
