packages:
  - apps/*
  - packages/*

catalog:
  '@astrojs/check': 0.9.4
  '@astrojs/starlight': ^0.36.0
  '@better-auth/cli': ^1.3.14
  '@biomejs/biome': 2.2.4
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': ^1.2.6
  '@sentry/tanstackstart-react': ^10.13.0
  '@tailwindcss/vite': 4.1.13
  '@tanstack/devtools-vite': ^0.3.3
  '@tanstack/react-devtools': ^0.7.0
  '@tanstack/react-query': ^5.90.1
  '@tanstack/react-query-devtools': ^5.90.1
  '@tanstack/react-router': ^1.131.50
  '@tanstack/react-router-devtools': ^1.131.50
  '@tanstack/react-router-ssr-query': ^1.131.50
  '@tanstack/react-start': ^1.131.50
  '@types/node': ^24.5.2
  '@types/react': 19.1.13
  '@types/react-dom': 19.1.9
  '@vitejs/plugin-react': ^5.0.3
  '@xstate/react': ^6.0.0
  astro: 5.13.10
  babel-plugin-react-compiler: 19.1.0-rc.3
  better-auth: ^1.3.14
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  effect: 3.17.14
  lucide-react: 0.544.0
  only-allow: ^1.2.1
  oxlint: 1.16.0
  react: ^19.1.1
  react-dom: ^19.1.1
  shadcn: ^3.3.1
  sharp: 0.34.4
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.13
  tsdown: 0.15.4
  tsx: ^4.20.5
  turbo: ^2.5.6
  tw-animate-css: 1.3.8
  typescript: ^5.9.2
  vite: ^7.1.7
  wrangler: ^4.38.0
  xstate: ^5.22.0

catalogMode: strict

cleanupUnusedCatalogs: true
