packages:
  - apps/*
  - packages/*

catalog:
  '@astrojs/check': 0.9.4
  '@astrojs/starlight': ^0.35.2
  '@biomejs/biome': 2.2.4
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-switch': ^1.2.6
  '@tailwindcss/postcss': ^4.1.13
  astro: 5.13.6
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  only-allow: ^1.2.1
  oxlint: 1.15.0
  postcss: ^8.5.6
  shadcn: ^3.3.1
  shadcn-prose: ^1.2.1
  sharp: 0.34.3
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tsdown: ^0.15.0
  tsx: ^4.20.5
  turbo: ^2.5.6
  tw-animate-css: ^1.3.8
  typescript: ^5.9.2

catalogMode: strict

cleanupUnusedCatalogs: true
