packages:
  - apps/*
  - packages/*

catalog:
  '@astrojs/check': 0.9.4
  '@astrojs/starlight': ^0.35.2
  '@biomejs/biome': 2.2.4
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': ^1.2.6
  '@tailwindcss/cli': ^4.1.13
  '@tailwindcss/postcss': ^4.1.13
  '@tanstack/devtools-vite': ^0.3.3
  '@tanstack/react-devtools': ^0.7.0
  '@tanstack/react-query': ^5.89.0
  '@tanstack/react-query-devtools': ^5.89.0
  '@tanstack/react-router': ^1.131.49
  '@tanstack/react-router-devtools': ^1.131.49
  '@tanstack/react-router-ssr-query': ^1.131.49
  '@tanstack/react-start': ^1.131.49
  '@types/react': 19.1.13
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.3
  astro: 5.13.6
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  lucide-react: ^0.544.0
  only-allow: ^1.2.1
  oxlint: 1.15.0
  postcss: ^8.5.6
  react: ^19.1.1
  react-dom: ^19.1.1
  shadcn: ^3.3.1
  sharp: 0.34.3
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tsdown: 0.15.0
  tsx: ^4.20.5
  turbo: ^2.5.6
  tw-animate-css: ^1.3.8
  typescript: ^5.9.2
  vite: ^7.1.6
  vite-tsconfig-paths: ^5.1.4

catalogMode: strict

cleanupUnusedCatalogs: true
