import {
  AUTH_COOKIE_PREFIX,
  EVENTUAL_CONSISTENCY_DELAY,
  IS_DEV,
  RANDOM_SEED,
} from "./configuration"
import { TEST_USER } from "./fake"
import {
  PRIVACY_POLICY_URL,
  TERMS_OF_USE_URL,
  WEBSITE_NAME,
} from "./information"

export {
  RANDOM_SEED,
  EVENTUAL_CONSISTENCY_DELAY,
  AUTH_COOKIE_PREFIX,
  IS_DEV,
  PRIVACY_POLICY_URL,
  TERMS_OF_USE_URL,
  WEBSITE_NAME,
  TEST_USER,
}
