name: CI

on:
  pull_request:

env:
  NODE_ENV: development
  CI: true
  POLAR_SUCCESS_URL: "https://previewDomain/success?checkout_id={CHECKOUT_ID}"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'full-ci') }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        task: [build, lint, test, typecheck]
    name: ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: ${{ matrix.task == 'build' }}
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
      - run: npm ci
      - run: npm run ${{ matrix.task }}
