name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  NODE_ENV: development,
  POLAR_SUCCESS_URL: "https://previewDomain/success?checkout_id={CHECKOUT_ID}"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [build, lint, test, typecheck]
    name: ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run ${{ matrix.task }}
